from __future__ import annotations

from typing import Mapping, Any


def _q(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_css(theme: Mapping[str, Any]) -> str:
    meta = theme["meta"]
    c = theme["colors"]
    return f"""/*
 Manifest
 Generated by MAKEETHEME.
 */

ManifestStyle
{{
    -kakaotalk-theme-name: {_q(meta['name'])};
    -kakaotalk-theme-version: {_q(meta['version'])};
    -kakaotalk-theme-url: {_q(meta.get('url', 'https://example.com'))};
    -kakaotalk-author-name: {_q(meta['authorName'])};
    -kakaotalk-theme-id: {_q(meta['iosThemeId'])};
}}

/*
 TabBar Style
 */

TabBarStyle-Main
{{
    background-color: {c['tabBarBackground']};
    -ios-background-image: 'maintabBgImage.png';

    -ios-friends-normal-icon-image: 'maintabIcoFriends.png';
    -ios-friends-selected-icon-image: 'maintabIcoFriendsSelected.png';
    -ios-chats-normal-icon-image: 'maintabIcoChats.png';
    -ios-chats-selected-icon-image: 'maintabIcoChatsSelected.png';
    -ios-now-normal-icon-image: 'maintabIcoNow.png';
    -ios-now-selected-icon-image: 'maintabIcoNowSelected.png';
    -ios-piccoma-normal-icon-image: 'maintabIcoPiccoma.png';
    -ios-piccoma-selected-icon-image: 'maintabIcoPiccomaSelected.png';
    -ios-shopping-normal-icon-image: 'maintabIcoShopping.png';
    -ios-shopping-selected-icon-image: 'maintabIcoShoppingSelected.png';
    -ios-call-normal-icon-image: 'maintabIcoCall.png';
    -ios-call-selected-icon-image: 'maintabIcoCallSelected.png';
    -ios-more-normal-icon-image: 'maintabIcoMore.png';
    -ios-more-selected-icon-image: 'maintabIcoMoreSelected.png';
    -ios-openchats-normal-icon-image: 'maintabIcoNow.png';
    -ios-openchats-selected-icon-image: 'maintabIcoNowSelected.png';
}}

/*
 MainView Style
 */

HeaderStyle-Main
{{
    -ios-text-color: {c['headerText']};
    -ios-tab-text-color: {c['tabText']};
    -ios-tab-highlighted-text-color: {c['tabHighlightedText']};
}}

MainViewStyle-Primary
{{
    background-color: {c['mainBackground']};
    -ios-background-image: 'mainBgImage.png';

    -ios-text-color: {c['mainText']};
    -ios-highlighted-text-color: {c['mainTextPressed']};
    -ios-description-text-color: {c['descriptionText']};
    -ios-description-highlighted-text-color: {c['descriptionTextPressed']};
    -ios-paragraph-text-color: {c['paragraphText']};
    -ios-paragraph-highlighted-text-color: {c['paragraphTextPressed']};

    -ios-normal-background-color: {c['cellBackground']};
    -ios-normal-background-alpha: 0.0;
    -ios-selected-background-color: {c['cellSelectedBackground']};
    -ios-selected-background-alpha: 0.05;
}}

MainViewStyle-Secondary
{{
    background-color: {c['mainBackground']};
}}

SectionTitleStyle-Main
{{
    border-color: {c['sectionBorder']};
    border-alpha: 0.09;
    -ios-text-color: {c['sectionText']};
    -ios-text-alpha: 1.0;
}}

/*
 Feature Style
 */

FeatureStyle-Primary
{{
    -ios-text-color: {c['featureText']};
}}

ButtonStyle-AddFriend
{{
    -ios-image: 'findBtnAddFriend.png';
}}

/*
 DefaultProfile Style
*/

DefaultProfileStyle
{{
    -ios-profile-images: 'profileImg01.png';
}}

/*
 ChatRoom Style
 */

BackgroundStyle-ChatRoom
{{
    background-color: {c['chatBackground']};
    -ios-background-image: 'chatroomBgImage.png';
}}

InputBarStyle-Chat
{{
    background-color: {c['inputBarBackground']};

    -ios-send-normal-background-color: {c['sendButtonBackground']};
    -ios-send-normal-foreground-color: {c['sendButtonText']};
    -ios-send-highlighted-background-color: {c['sendButtonPressedBackground']};
    -ios-send-highlighted-foreground-color: {c['sendButtonPressedText']};

    -ios-button-normal-foreground-color: {c['inputIcon']};
    -ios-button-highlighted-foreground-color: {c['inputIconPressed']};

    -ios-button-text-color: {c['inputButtonText']};
    -ios-button-normal-background-color: {c['inputButtonBackground']};
    -ios-button-normal-background-alpha: 0.04;
}}

/*
 Message Style
 */

MessageCellStyle-Send
{{
    -ios-background-image: 'chatroomBubbleSend01.png' 17px 17px;
    -ios-selected-background-image: 'chatroomBubbleSend01Selected.png' 17px 17px;
    -ios-group-background-image: 'chatroomBubbleSend02.png' 17px 17px;
    -ios-group-selected-background-image: 'chatroomBubbleSend02Selected.png' 17px 17px;
    -ios-title-edgeinsets: 10px 11px 7px 17px;
    -ios-group-title-edgeinsets: 10px 11px 7px 17px;

    -ios-text-color: {c['messageSendText']};
    -ios-selected-text-color: {c['messageSendText']};
    -ios-unread-text-color: {c['unreadText']};
}}

MessageCellStyle-Receive
{{
    -ios-background-image: 'chatroomBubbleReceive01.png' 22px 17px;
    -ios-selected-background-image: 'chatroomBubbleReceive01Selected.png' 22px 17px;
    -ios-group-background-image: 'chatroomBubbleReceive02.png' 22px 17px;
    -ios-group-selected-background-image: 'chatroomBubbleReceive02Selected.png' 22px 17px;
    -ios-title-edgeinsets: 10px 17px 7px 11px;
    -ios-group-title-edgeinsets: 10px 17px 7px 11px;

    -ios-text-color: {c['messageReceiveText']};
    -ios-selected-text-color: {c['messageReceiveText']};
    -ios-unread-text-color: {c['unreadText']};
}}

/*
 Passcode Style
 */

BackgroundStyle-Passcode
{{
    background-color: {c['passcodeBackground']};
    -ios-background-image: 'passcodeBgImage.png';
}}

LabelStyle-PasscodeTitle
{{
    -ios-text-color: {c['passcodeTitle']};
}}

PasscodeStyle
{{
    -ios-bullet-first-image: 'passcodeImgCode01.png';
    -ios-bullet-second-image: 'passcodeImgCode02.png';
    -ios-bullet-third-image: 'passcodeImgCode03.png';
    -ios-bullet-fourth-image: 'passcodeImgCode04.png';

    -ios-bullet-selected-first-image: 'passcodeImgCode01Selected.png';
    -ios-bullet-selected-second-image: 'passcodeImgCode02Selected.png';
    -ios-bullet-selected-third-image: 'passcodeImgCode03Selected.png';
    -ios-bullet-selected-fourth-image: 'passcodeImgCode04Selected.png';

    -ios-keypad-background-color: {c['passcodeKeypadBackground']};
    -ios-keypad-text-normal-color: {c['passcodeKeypadText']};
    -ios-keypad-number-highlighted-image : 'passcodeKeypadPressed.png';
}}

/*
 Message Notification Bar Style
 */

BackgroundStyle-MessageNotificationBar
{{
    background-color: {c['notificationBackground']};
}}

LabelStyle-MessageNotificationBarName
{{
    -ios-text-color: {c['notificationName']};
}}

LabelStyle-MessageNotificationBarMessage
{{
    -ios-text-color: {c['notificationMessage']};
}}

/*
 Direct Share
*/

BackgroundStyle-DirectShareBar
{{
    background-color: {c['directShareBackground']};
}}
"""
